force-app/main/default/objects/Blanket_Row__c/Blanket_Row__c.object-meta.xml
<CustomObject>
    <description>A single row on the blanket representing a given day of the year</description>
    <label>Blanket Row</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Blanket Row Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blanket Rows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blanket_Row__c/fields/Color_Scheme_Item__c.field-meta.xml
<CustomField>
    <fullName>Color_Scheme_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Color Scheme Item that defines this Blanket Row&apos;s</description>
    <inlineHelpText>The Color Scheme Item that defines this Blanket Row&apos;s</inlineHelpText>
    <label>Color Scheme Item</label>
    <referenceTo>Color_Scheme_Item__c</referenceTo>
    <relationshipLabel>Blanket Rows</relationshipLabel>
    <relationshipName>Blanket_Rows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blanket_Row__c/fields/DateWeather__c.field-meta.xml
<CustomField>
    <fullName>DateWeather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship to a DateWeather record where this BlanketRow can pull a Date and Temp</description>
    <inlineHelpText>Relationship to a DateWeather record where this BlanketRow can pull a Date and Temp</inlineHelpText>
    <label>DateWeather</label>
    <referenceTo>DateWeather__c</referenceTo>
    <relationshipLabel>Blanket Rows</relationshipLabel>
    <relationshipName>Blanket_Rows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Color_Scheme_Item__c/Color_Scheme_Item__c.object-meta.xml
<CustomObject>
    <description>A row of the color scheme containing a color and the temperature range it represents</description>
    <label>Color Scheme Item</label>
    <nameField>
        <label>Color Scheme Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Color Scheme Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Color_Scheme_Item__c/fields/Max_Temp__c.field-meta.xml
<CustomField>
    <fullName>Max_Temp__c</fullName>
    <description>Max Temp that this Color Scheme Items</description>
    <inlineHelpText>Max Temp that this Color Scheme Items</inlineHelpText>
    <label>Max Temp</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Color_Scheme_Item__c/fields/Min_Temp__c.field-meta.xml
<CustomField>
    <fullName>Min_Temp__c</fullName>
    <description>Min Temp that this Color Scheme Item Represents</description>
    <inlineHelpText>Min Temp that this Color Scheme Item Represents</inlineHelpText>
    <label>Min Temp</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DateWeather__c/DateWeather__c.object-meta.xml
<CustomObject>
    <description>A record representing a given day&apos;s weather</description>
    <label>DateWeather</label>
    <nameField>
        <displayFormat>DW-{0000}</displayFormat>
        <label>DateWeather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DateWeathers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DateWeather__c/fields/Avg_Temp__c.field-meta.xml
<CustomField>
    <fullName>Avg_Temp__c</fullName>
    <description>Avg. Daily Temp for this Date</description>
    <inlineHelpText>Avg. Daily Temp for this Date</inlineHelpText>
    <label>Avg. Temp</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BlanketAppService.cls
public with sharing class BlanketAppService {
    //static methods to support the BlanketApp (currently LWC, could be Flow, etc)
    public static List<DateWeather__c> getDateWeatherByYear(Integer year){
        Date minDate = Date.newInstance(year, 01, 01);
        Date maxDate = minDate.addYears(+1).addDays(-1);
        return [SELECT Id, Date__c, Avg_Temp__c 
                FROM DateWeather__c 
                WHERE Date__c >= :minDate AND Date__c <= :maxDate ];
    }


    public static List<Blanket_Row__c> createBlanketForSchemeAndDateWeather(List<Color_Scheme_Item__c> colorSchemeItemList, List<DateWeather__c> dateWeatherList){
        List<Blanket_Row__c> blanketRowList = New List<Blanket_Row__c>();

        //iterate through dateWeatherList
        for(DateWeather__c dW : dateWeatherList){
            for(Color_Scheme_Item__c cSI : colorSchemeItemList){
                if(dW.Avg_Temp__c >= cSI.Min_Temp__c && dW.Avg_Temp__c <= cSI.Max_Temp__c){
                    blanketRowList.add(createBlanketRow(dW, cSI));
                    break;
                }
            }
        }
        return blanketRowList;
    }

    private static Blanket_Row__c createBlanketRow(DateWeather__c dW, Color_Scheme_Item__c cSI){
        //ideally, associating by object instead of Id lets the values carry over and be readable in the LWC
        return New Blanket_Row__c(
            DateWeather__r = dW,
            Color_Scheme_Item__r = cSI
        );
    }

    @AuraEnabled(cacheable=true)
    public static List<Blanket_Row__c> createBlanketForSchemeAndDateWeather(List<Color_Scheme_Item__c> colorSchemeItemList, Integer year){
        System.debug(colorSchemeItemList);

        return createBlanketForSchemeAndDateWeather(colorSchemeItemList, getDateWeatherByYear(year));
    }

    public BlanketAppService() {
    }
}